name: MLS weekly scrape

# When to run this action
on:
  schedule:
    # This runs at 8:00 AM UTC every Monday.
    # Use https://crontab.guru to create your own schedule.
    - cron: '0 8 * * 1'
  
  # This line lets you run it manually from the Actions tab
  workflow_dispatch:

# The tasks to perform
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: scrape.py # <-- IMPORTANT: CHANGE THIS
